//==================================================================================================
/*
  EVE - Expressive Vector Engine
  Copyright : EVE Contributors & Maintainers
  SPDX-License-Identifier: MIT
*/
//==================================================================================================
#pragma once

#include <eve/module/math/constant/euler.hpp>
#include <eve/module/math/constant/egamma.hpp>
#include <eve/module/math/constant/halfeps.hpp>
#include <eve/module/math/constant/invlog10_2.hpp>
#include <eve/module/math/constant/invlog_10.hpp>
#include <eve/module/math/constant/invlog_2.hpp>
#include <eve/module/math/constant/invpi.hpp>
#include <eve/module/math/constant/invsqrt_2.hpp>
#include <eve/module/math/constant/invsqrtpi.hpp>
#include <eve/module/math/constant/log_2.hpp>
#include <eve/module/math/constant/log_10.hpp>
#include <eve/module/math/constant/log2_e.hpp>
#include <eve/module/math/constant/log10_e.hpp>
#include <eve/module/math/constant/maxlog10.hpp>
#include <eve/module/math/constant/maxlog2.hpp>
#include <eve/module/math/constant/maxlog.hpp>
#include <eve/module/math/constant/minlog10denormal.hpp>
#include <eve/module/math/constant/minlog10.hpp>
#include <eve/module/math/constant/minlog2denormal.hpp>
#include <eve/module/math/constant/minlog2.hpp>
#include <eve/module/math/constant/minlogdenormal.hpp>
#include <eve/module/math/constant/minlog.hpp>
#include <eve/module/math/constant/oneotwoeps.hpp>
#include <eve/module/math/constant/phi.hpp>
#include <eve/module/math/constant/pi.hpp>
#include <eve/module/math/constant/pio_4.hpp>
#include <eve/module/math/constant/sqrt_2.hpp>
#include <eve/module/math/constant/sqrt_3.hpp>
#include <eve/module/math/constant/twoopi.hpp>
#include <eve/module/math/constant/twopi.hpp>

//boost math constants
#include <eve/module/math/constant/catalan.hpp>
#include <eve/module/math/constant/cbrt_pi.hpp>
#include <eve/module/math/constant/cosh_one.hpp>
#include <eve/module/math/constant/cos_one.hpp>
#include <eve/module/math/constant/egamma.hpp>
#include <eve/module/math/constant/egamma_sqr.hpp>
#include <eve/module/math/constant/euler_pow_pi.hpp>
#include <eve/module/math/constant/exp_minus_half.hpp>
#include <eve/module/math/constant/exp_minus_one.hpp>
#include <eve/module/math/constant/extreme_value_skewness.hpp>
#include <eve/module/math/constant/four_minus_pi.hpp>
#include <eve/module/math/constant/four_thirds_pi.hpp>
#include <eve/module/math/constant/glaisher.hpp>
#include <eve/module/math/constant/half_pi.hpp>
#include <eve/module/math/constant/half_root_two.hpp>
#include <eve/module/math/constant/inv_cbrt_pi.hpp>
#include <eve/module/math/constant/inv_egamma.hpp>
#include <eve/module/math/constant/inv_log_phi.hpp>
#include <eve/module/math/constant/inv_log10_e.hpp>
#include <eve/module/math/constant/inv_pi.hpp>
#include <eve/module/math/constant/inv_root_pi.hpp>
#include <eve/module/math/constant/inv_root_two.hpp>
#include <eve/module/math/constant/inv_root_two_pi.hpp>
#include <eve/module/math/constant/inv_two_pi.hpp>
#include <eve/module/math/constant/khinchin.hpp>
#include <eve/module/math/constant/log_log_2.hpp>
#include <eve/module/math/constant/log_phi.hpp>
#include <eve/module/math/constant/pi_cubed.hpp>
#include <eve/module/math/constant/pi_minus_three.hpp>
#include <eve/module/math/constant/pi_pow_euler.hpp>
#include <eve/module/math/constant/pi_sqr.hpp>
#include <eve/module/math/constant/pi_sqr_o_six.hpp>
#include <eve/module/math/constant/quarter_pi.hpp>
#include <eve/module/math/constant/rayleigh_kurtosis_excess.hpp>
#include <eve/module/math/constant/rayleigh_kurtosis.hpp>
#include <eve/module/math/constant/rayleigh_skewness.hpp>
#include <eve/module/math/constant/root_euler.hpp>
#include <eve/module/math/constant/root_half_pi.hpp>
#include <eve/module/math/constant/root_inv_pi.hpp>
#include <eve/module/math/constant/root_log_four.hpp>
#include <eve/module/math/constant/root_pi.hpp>
#include <eve/module/math/constant/root_three.hpp>
#include <eve/module/math/constant/root_two.hpp>
#include <eve/module/math/constant/root_two_o_pi.hpp>
#include <eve/module/math/constant/root_two_pi.hpp>
#include <eve/module/math/constant/sinh_one.hpp>
#include <eve/module/math/constant/sin_one.hpp>
#include <eve/module/math/constant/sixth.hpp>
#include <eve/module/math/constant/sixth_pi.hpp>
#include <eve/module/math/constant/third.hpp>
#include <eve/module/math/constant/third_pi.hpp>
#include <eve/module/math/constant/three_quarters.hpp>
#include <eve/module/math/constant/three_quarters_pi.hpp>
#include <eve/module/math/constant/two_o_pi.hpp>
#include <eve/module/math/constant/two_o_root_pi.hpp>
#include <eve/module/math/constant/two_pi.hpp>
#include <eve/module/math/constant/two_thirds.hpp>
#include <eve/module/math/constant/two_thirds_pi.hpp>
#include <eve/module/math/constant/zeta_three.hpp>
#include <eve/module/math/constant/zeta_two.hpp>
