//==================================================================================================
/*
  EVE - Expressive Vector Engine
  Copyright : EVE Project Contributors
  SPDX-License-Identifier: BSL-1.0
*/
//==================================================================================================
#pragma once

#include <eve/module/math/catalan.hpp>
#include <eve/module/math/cbrt_pi.hpp>
#include <eve/module/math/cos_1.hpp>
#include <eve/module/math/cosh_1.hpp>
#include <eve/module/math/egamma.hpp>
#include <eve/module/math/egamma.hpp>
#include <eve/module/math/egamma_sqr.hpp>
#include <eve/module/math/epso_2.hpp>
#include <eve/module/math/euler.hpp>
#include <eve/module/math/exp_pi.hpp>
#include <eve/module/math/extreme_value_skewness.hpp>
#include <eve/module/math/four_minus_pi.hpp>
#include <eve/module/math/four_pio_3.hpp>
#include <eve/module/math/glaisher.hpp>
#include <eve/module/math/inv_2eps.hpp>
#include <eve/module/math/invcbrt_pi.hpp>
#include <eve/module/math/inv_egamma.hpp>
#include <eve/module/math/inv_e.hpp>
#include <eve/module/math/invlog10_2.hpp>
#include <eve/module/math/invlog10_e.hpp>
#include <eve/module/math/invlog_10.hpp>
#include <eve/module/math/invlog_2.hpp>
#include <eve/module/math/invlog_phi.hpp>
#include <eve/module/math/inv_pi.hpp>
#include <eve/module/math/inv_pi.hpp>
#include <eve/module/math/invsqrt_2.hpp>
#include <eve/module/math/khinchin.hpp>
#include <eve/module/math/log10_e.hpp>
#include <eve/module/math/log_10.hpp>
#include <eve/module/math/log2_e.hpp>
#include <eve/module/math/log_2.hpp>
#include <eve/module/math/loglog_2.hpp>
#include <eve/module/math/log_phi.hpp>
#include <eve/module/math/maxlog10.hpp>
#include <eve/module/math/maxlog2.hpp>
#include <eve/module/math/maxlog.hpp>
#include <eve/module/math/minlog10denormal.hpp>
#include <eve/module/math/minlog10.hpp>
#include <eve/module/math/minlog2denormal.hpp>
#include <eve/module/math/minlog2.hpp>
#include <eve/module/math/minlogdenormal.hpp>
#include <eve/module/math/minlog.hpp>
#include <eve/module/math/phi.hpp>
#include <eve/module/math/pi2.hpp>
#include <eve/module/math/pi2o_16.hpp>
#include <eve/module/math/pi2o_6.hpp>
#include <eve/module/math/pi3.hpp>
#include <eve/module/math/pi.hpp>
#include <eve/module/math/pi_minus_3.hpp>
#include <eve/module/math/pio_3.hpp>
#include <eve/module/math/pio_4.hpp>
#include <eve/module/math/pio_6.hpp>
#include <eve/module/math/pi_pow_e.hpp>
#include <eve/module/math/rayleigh_kurtosis_excess.hpp>
#include <eve/module/math/rayleigh_kurtosis.hpp>
#include <eve/module/math/rayleigh_skewness.hpp>
#include <eve/module/math/rsqrt_2pi.hpp>
#include <eve/module/math/rsqrt_e.hpp>
#include <eve/module/math/rsqrt_pi.hpp>
#include <eve/module/math/rsqrt_pi.hpp>
#include <eve/module/math/rsqrt_pi.hpp>
#include <eve/module/math/rsqrt_pio_2.hpp>
#include <eve/module/math/sin_1.hpp>
#include <eve/module/math/sinh_1.hpp>
#include <eve/module/math/sixth.hpp>
#include <eve/module/math/sqrt_2.hpp>
#include <eve/module/math/sqrt_2.hpp>
#include <eve/module/math/sqrt_2pi.hpp>
#include <eve/module/math/sqrt_3.hpp>
#include <eve/module/math/sqrt_3.hpp>
#include <eve/module/math/sqrt_e.hpp>
#include <eve/module/math/sqrtlog_4.hpp>
#include <eve/module/math/sqrt_pi.hpp>
#include <eve/module/math/sqrt_pio_2.hpp>
#include <eve/module/math/third.hpp>
#include <eve/module/math/three_o_4.hpp>
#include <eve/module/math/three_pio_4.hpp>
#include <eve/module/math/two_o_3.hpp>
#include <eve/module/math/two_o_pi.hpp>
#include <eve/module/math/two_o_pi.hpp>
#include <eve/module/math/two_o_sqrt_pi.hpp>
#include <eve/module/math/two_pi.hpp>
#include <eve/module/math/two_pio_3.hpp>
#include <eve/module/math/zeta_2.hpp>
#include <eve/module/math/zeta_3.hpp>
