#!/bin/bash
# crée les fichiers de la fonction $2 à partir des fichiers de $1 
# ce fichier doit être dans le répertoire de base de eve

if [ "$#" -eq 0 ]
then
  echo 'usage: create_func_from_to $1 $2:  create the files of function $2 from the files of the function $1'
  echo 'of course if the names are properly changed the code has to be edited'
  return
elif [ "$#" -eq 1 ]
then
  echo "create_func_from_to: invalid number of arguments"
  return
else
  echo "create the files of a function "$2" from the files of the function "$1
fi
from=$1
to=$2
FROM="${from^^}"
TO="${to^^}"
icitte=$(pwd)
incl=include/eve/

files=$(find $icitte/$incl -type f -name $from.hpp)
for fil in $files 
do
  newfil=${fil%/$from.hpp}/$to.hpp
  cp -n $fil $newfil
  sed -i "s/$from/$to/g" $newfil
  sed -i "s/$FROM/$TO/g" $newfil    
done

cd $icitte