#!/bin/bash
# crée les fichiers de la fonction $2 à partir des fichiers de $1 
# ce fichier doit être dans le répertoire de base de eve

if [ "$#" -eq 0 ]
then
  echo 'usage: create_func_and_tests $1 $2:  create the files of function $2 from the files of the function $1'
  echo 'of course if the names are properly changed the code has to be edited'
  return
elif [ "$#" -eq 1 ]
then
  echo "create_func_and_tests: invalid number of arguments"
  return
else
  echo "create the files of a function "$2" from the files of the function "$1
fi

from=$1
to=$2

source ./create_func_from_to $from $to
source ./create_simd_test_from_to $from $to
source ./create_scalar_test_from_to $from $to
source ./create_doc_test_from_to $from $to
#source ./create_bench_from_to $from $to

#icitte=$(pwd)

#nrstf=include/eve_copie/doc/manual/functions/predicate
#rstf=include/eve/doc/manual/functions/predicate  
#cp $icitte/$nrstf/to.rst $icitte/$rstf/to.rst
