#!/bin/bash
# crée les fichiers de test simd de la fonction $2 à partir des fichiers de $1, $3 donnant le chemin de eve 

if [ "$#" -eq 0 ]
then
  echo 'usage: create_simd_test_from_to $1 $2 $3:  create the simd tests of a function $2 from the files of the function $1'
  echo '                                           $3 is the path to eve (by default pwd)'
  return
elif [ "$#" -eq 1 ]
then
  echo "create_simd_test_from_to: invalid number of arguments"
  return
elif [ "$#" -eq 2 ]
then
  echo "create the simd tests of a function "$2" from the files of the function "$1
  rootdir=$(pwd)
  echo "root dir is "$rootdir
else
  echo "create the simd tests of a function "$2" from the files of the function "$1
  rootdir=$3
  echo "root dir is "$rootdir
fi
from=$1
to=$2
FROM="${from^^}"
TO="${to^^}"
icitte=$(pwd)
testsimd=test/unit/module/core/simd

mkdir -p $rootdir/$testsimd/$to 
cp -pR $rootdir/$testsimd/$from/* $icitte/$testsimd/$to  

cd  $rootdir/$testsimd/$to
dirs=$(ls -d */ 2>/dev/null || true)

if [ -z "${dirs}" ]
then
  cd  $rootdir/$testsimd/$to
  mv $from.hpp $to.hpp
  sed -i "s/$from/$to/g" *.?pp
  sed -i "s/$FROM/$TO/g" $to.hpp  
  sed -i "/list_tests..simd\/$from. /{h;s/$from/$to/;H;x}" ../../CMakeLists.txt
else
  for dir in $(ls -d */)
  do
    d=${dir::-1}
    cd  $rootdir/$testsimd/$to/$d
    mv $from.hpp $to.hpp
    sed -i "s/$from/$to/g" *.?pp
    sed -i "s/$FROM/$TO/g" $to.hpp  
    sed -i "/list_tests..simd\/$from\/$d. /{h;s/$from/$to/;H;x}" ../../../CMakeLists.txt
  done
fi

cd $rootdir