##==================================================================================================
##  EVE - Expressive Vector Engine
##  Copyright : EVE Contributors & Maintainers
##  SPDX-License-Identifier: MIT
##==================================================================================================
#!/usr/bin/env bash


echo "<!--"
echo "  EVE -  Expressive Vector Engine"
echo "  Copyright : EVE Contributors & Maintainers"
echo "  SPDX-License-Identifier: MIT"
echo ""
echo "  Licensed under the MIT License <http://opensource.org/licenses/MIT>."
echo "  SPDX-License-Identifier: MIT"
echo " -->"
echo "<meta charset=\"utf-8\" lang=\"en\">"
echo "                       **Expressive Vector Engine**"
echo "                           \`eve::$1\`"
echo "<br>"
echo ""
echo "  (insert ../../../crumbs.html here)"
echo ""
echo "Synopsis"
echo "===================================================================================================="
echo "**Required header:** <script type=\"preformatted\">\`#include <eve/function/$1.hpp>\`</script>"
echo ""
echo "<script type=\"preformatted\">"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ c++"
echo "namespace eve"
echo "{"
echo "  inline constexpr /*unspecified*/ $1 = /*unspecified*/;"
echo "}"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "</script>"
echo "Function object representing **TODO: FILL THIS BLANK**."
echo ""
echo "Member functions"
echo "===================================================================================================="
echo "<script type=\"preformatted\">"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ c++"
echo "template<**TODO: FILL THIS BLANK**>"
echo "auto operator()( **TODO: FILL THIS BLANK**) const noexcept;"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "</script>"
echo "**TODO: FILL THIS BLANK**"
echo ""
echo "Parameters"
echo "----------------------------------------------------------------------------------------------------"
echo "\`x\`"
echo ":   **TODO: FILL THIS BLANK**"
echo ""
echo "OTHER PARAMETERS"
echo ":   **TODO: FILL THIS BLANK IF NEEDED BUT RESPECT THE : FORMATTING**"
echo ""
echo "Return value"
echo "----------------------------------------------------------------------------------------------------"
echo "<span class=\"smallskip\"></span>"
echo "For **TODO: FILL THIS BLANK**:"
echo ""
echo "<script type=\"preformatted\">"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ c++"
echo "auto r = $1(**TODO: FILL THIS BLANK**);"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "</script>"
echo ""
echo "is semantically equivalent to:"
echo ""
echo "<script type=\"preformatted\">"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ c++"
echo "Target r;"
echo ""
echo "if constexpr( scalar_value<T> )"
echo "{"
echo "  **TODO: FILL THIS BLANK**"
echo "}"
echo "else if constexpr( simd_value<T> )"
echo "{"
echo "  **TODO: FILL THIS BLANK**"
echo "}"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "</script>"
echo ""
echo "  <!--(insert ../../src/$1.src.html here)-->"
echo ""
echo "  <!--(insert ../../out/$1.out.html here)-->"
echo ""
echo "See Also"
echo "===================================================================================================="
echo ""
echo "**TODO: FILL THIS BLANK OR REMOVE THE SECTION ALTOGETHER**"
echo ""
echo "<!-- End of Document -->"
echo "<link rel=\"stylesheet\" href=\"../../../eve.css\">"
echo "<!-- Markdeep: -->"
echo "<script>markdeepOptions={tocStyle:'medium'};</script>"
echo "<script src=\"../../../markdeep.min.js\"></script>"
echo "<script src=\"https://casual-effects.com/markdeep/latest/markdeep.min.js?\"></script>"
