var hierarchy =
[
    [ "eve::abi< Type, Lanes >", "structeve_1_1abi.html", null ],
    [ "eve::aligned_allocator< T, Lanes >", "structeve_1_1aligned__allocator.html", null ],
    [ "eve::aligned_ptr< Type, Lanes >", "structeve_1_1aligned__ptr.html", null ],
    [ "eve::as< T >", "structeve_1_1as.html", null ],
    [ "eve::as_pattern< F >", "structeve_1_1as__pattern.html", null ],
    [ "backward_iterator", "structbackward__iterator.html", null ],
    [ "eve::algo::views::backward_iterator< I >", "structeve_1_1algo_1_1views_1_1backward__iterator.html", null ],
    [ "backward_range", "structbackward__range.html", null ],
    [ "eve::algo::views::backward_range< R >", "structeve_1_1algo_1_1views_1_1backward__range.html", null ],
    [ "eve::common_compatible< Ts >", "structeve_1_1common__compatible.html", null ],
    [ "eve::common_type< Ts >", "structeve_1_1common__type.html", null ],
    [ "eve::constant", "structeve_1_1constant.html", null ],
    [ "converting_iterator", "structconverting__iterator.html", null ],
    [ "eve::algo::views::converting_iterator< I, T >", "structeve_1_1algo_1_1views_1_1converting__iterator.html", null ],
    [ "converting_range", "structconverting__range.html", null ],
    [ "eve::algo::views::converting_range< R, T >", "structeve_1_1algo_1_1views_1_1converting__range.html", null ],
    [ "eve::decorators< Settings >", "structeve_1_1decorators.html", null ],
    [ "eve::element_type< T >", "structeve_1_1element__type.html", null ],
    [ "eve::elementwise", "structeve_1_1elementwise.html", null ],
    [ "eve::fixed< Cardinal >", "structeve_1_1fixed.html", null ],
    [ "eve::fixed< 1 >", "structeve_1_1fixed.html", [
      [ "eve::cardinal< Type >", "structeve_1_1cardinal.html", null ]
    ] ],
    [ "eve::fixed< ABI::template fundamental_cardinal< Type > >", "structeve_1_1fixed.html", [
      [ "eve::fundamental_cardinal< Type, ABI >", "structeve_1_1fundamental__cardinal.html", null ]
    ] ],
    [ "eve::if_< C >", "structeve_1_1if__.html", null ],
    [ "eve::ignore_all_", "structeve_1_1ignore__all__.html", null ],
    [ "eve::ignore_extrema", "structeve_1_1ignore__extrema.html", null ],
    [ "eve::ignore_first", "structeve_1_1ignore__first.html", null ],
    [ "eve::ignore_last", "structeve_1_1ignore__last.html", null ],
    [ "eve::ignore_none_", "structeve_1_1ignore__none__.html", null ],
    [ "eve::algo::views::iota_with_step_iterator< T, N >", "structeve_1_1algo_1_1views_1_1iota__with__step__iterator.html", null ],
    [ "iota_with_step_iterator", "structiota__with__step__iterator.html", null ],
    [ "eve::keep_between", "structeve_1_1keep__between.html", null ],
    [ "eve::keep_first", "structeve_1_1keep__first.html", null ],
    [ "eve::keep_last", "structeve_1_1keep__last.html", null ],
    [ "eve::logical< T >", "structeve_1_1logical_3_01T_01_4.html", null ],
    [ "eve::algo::views::map_iterator< I, LoadOp, StoreOp >", "structeve_1_1algo_1_1views_1_1map__iterator.html", null ],
    [ "map_iterator", "structmap__iterator.html", null ],
    [ "map_load_op", "structmap__load__op.html", null ],
    [ "eve::algo::views::map_range< R, LoadOp, StoreOp >", "structeve_1_1algo_1_1views_1_1map__range.html", null ],
    [ "map_range", "structmap__range.html", null ],
    [ "map_store_op", "structmap__store__op.html", null ],
    [ "eve::algo::nothing_t", "structeve_1_1algo_1_1nothing__t.html", null ],
    [ "eve::or_< C, V >", "structeve_1_1or__.html", null ],
    [ "eve::pattern_t< I >", "structeve_1_1pattern__t.html", null ],
    [ "eve::platform", "structeve_1_1platform.html", null ],
    [ "eve::algo::ptr_iterator< Ptr, Cardinal >", "structeve_1_1algo_1_1ptr__iterator.html", null ],
    [ "eve::algo::range_ref_wrapper< Rng >", "structeve_1_1algo_1_1range__ref__wrapper.html", null ],
    [ "eve::aligned_allocator< T, Lanes >::rebind< U >", "structeve_1_1aligned__allocator_1_1rebind.html", null ],
    [ "eve::reduction", "structeve_1_1reduction.html", null ],
    [ "relaxed_iterator", "structrelaxed__iterator.html", null ],
    [ "relaxed_range", "structrelaxed__range.html", null ],
    [ "relaxed_sentinel_for", "structrelaxed__sentinel__for.html", null ],
    [ "eve::algo::views::reverse_iterator< I >", "structeve_1_1algo_1_1views_1_1reverse__iterator.html", null ],
    [ "reverse_iterator", "structreverse__iterator.html", null ],
    [ "eve::algo::views::reverse_range< R >", "structeve_1_1algo_1_1views_1_1reverse__range.html", null ],
    [ "reverse_range", "structreverse__range.html", null ],
    [ "eve::soa_ptr< Ptrs >", "structeve_1_1soa__ptr.html", null ],
    [ "eve::stack_buffer< T >", "structeve_1_1stack__buffer.html", null ],
    [ "eve::struct_support< Self, Fields >", "structeve_1_1struct__support.html", null ],
    [ "eve::struct_support< complex< Type >, Type, Type >", "structeve_1_1struct__support.html", [
      [ "eve::complex< Type >", "structeve_1_1complex.html", null ]
    ] ],
    [ "eve::support_options< Tag >", "structeve_1_1support__options.html", null ],
    [ "eve::supports_like< Wrapper, Self >", "structeve_1_1supports__like.html", null ],
    [ "eve::supports_ordering< Type >", "structeve_1_1supports__ordering.html", null ],
    [ "eve::top_bits< Logical >", "structeve_1_1top__bits.html", null ],
    [ "eve::algo::traits< Settings >", "structeve_1_1algo_1_1traits.html", null ],
    [ "eve::underlying_type< Ts >", "structeve_1_1underlying__type.html", null ],
    [ "eve::underlying_type< T >", "structeve_1_1underlying__type.html", null ],
    [ "eve::unsupported_call< Signature >", "structeve_1_1unsupported__call.html", null ],
    [ "eve::detail::wide_storage< as_logical_register_t< Type, Cardinal, abi_t< Type, Cardinal > > >", null, [
      [ "eve::logical< wide< Type, Cardinal > >", "structeve_1_1logical_3_01wide_3_01Type_00_01Cardinal_01_4_01_4.html", null ]
    ] ],
    [ "eve::detail::wide_storage< as_register_t< Type, Cardinal, abi_t< Type, Cardinal > > >", null, [
      [ "eve::wide< Type, Cardinal >", "structeve_1_1wide.html", null ]
    ] ],
    [ "eve::detail::wide_storage< as_register_t< Type, N, abi_t< Type, N > > >", null, [
      [ "eve::wide< value_type_t< I >, N >", "structeve_1_1wide.html", null ],
      [ "eve::wide< value_type, N >", "structeve_1_1wide.html", null ]
    ] ],
    [ "eve::algo::views::zip_iterator< Is >", "structeve_1_1algo_1_1views_1_1zip__iterator.html", null ],
    [ "zip_iterator", "structzip__iterator.html", null ],
    [ "eve::algo::views::zip_range< Rngs >", "structeve_1_1algo_1_1views_1_1zip__range.html", null ],
    [ "zip_range", "structzip__range.html", null ]
];