var searchData=
[
  ['tag_20invoke_20protocol_0',['Generalized Tag Invoke Protocol',['../group__invoke.html',1,'']]],
  ['tag_5finvoke_5fresult_1',['tag_invoke_result',['../group__invoke.html#gac02d96a9e94b826ce20e7e29451a96e3',1,'eve']]],
  ['tag_5fof_2',['tag_of',['../group__invoke.html#ga8dde0862945d94fceab4dbc0b0b29bf3',1,'eve']]],
  ['targets_3',['Handling Multiple Architecture Targets',['../multiarch.html',1,'tutorials']]],
  ['template_4',['template',['..//__w/eve/eve/include/eve/arch/expected_cardinal.hpp#autotoc_md2',1,'Helper variable template'],['../structeve_1_1fundamental__cardinal.html#autotoc_md5',1,'Helper variable template'],['../structeve_1_1supports__ordering.html#autotoc_md77',1,'Helper variable template']]],
  ['testing_5',['Building for Testing',['../dev_cmake.html',1,'eve-dev']]],
  ['tests_6',['tests',['../dev_cmake.html#autotoc_md91',1,'Compiling EVE Random Tests'],['../dev_cmake.html#autotoc_md90',1,'Compiling EVE Unit Tests']]],
  ['the_20documentation_7',['Building the Documentation',['../install.html#autotoc_md111',1,'']]],
  ['the_20dynamic_20function_20hub_8',['Writing the dynamic function hub',['../multiarch.html#autotoc_md162',1,'']]],
  ['the_20expressive_20vector_20engine_9',['The Expressive Vector Engine',['../index.html',1,'']]],
  ['the_20issue_10',['The Issue',['../multiarch.html#autotoc_md159',1,'']]],
  ['the_20kernel_11',['Writing the kernel',['../multiarch.html#autotoc_md161',1,'']]],
  ['the_20library_12',['the library',['../install.html#autotoc_md110',1,'Setting up the Library'],['../install.html#autotoc_md112',1,'Using the library']]],
  ['the_20one_20big_20news_20for_20this_20release_3a_20sve_13',['The One Big News for this release: SVE',['../changelog.html#autotoc_md122',1,'']]],
  ['the_20source_14',['Retrieving the source',['../install.html#autotoc_md102',1,'']]],
  ['there_20is_20a_20match_15',['What if I know there is a match?',['..//__w/eve/eve/include/eve/module/core/regular/first_true.hpp#autotoc_md46',1,'']]],
  ['this_20release_3a_20sve_16',['The One Big News for this release: SVE',['../changelog.html#autotoc_md122',1,'']]],
  ['to_20dynamic_20dispatch_17',['From static to dynamic dispatch',['../multiarch.html#autotoc_md160',1,'']]],
  ['to_20simd_20processing_18',['Adapting UDT to SIMD processing',['../intro-04.html#autotoc_md155',1,'']]],
  ['to_20simd_20using_20eve_3a_3awide_19',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md144',1,'']]],
  ['top_5fbits_20',['top_bits',['../structeve_1_1top__bits.html',1,'eve']]],
  ['toward_20simd_20algorithms_21',['Toward SIMD Algorithms',['../intro-02.html#autotoc_md149',1,'']]],
  ['traits_22',['traits',['../glossary_semantic.html#autotoc_md95',1,'ABI traits'],['../algo_rationale.html#autotoc_md88',1,'Algorithms traits'],['../structeve_1_1algo_1_1traits.html',1,'eve::algo::traits&lt; Settings &gt;'],['../group__traits.html',1,'Type traits']]],
  ['trigonometric_23',['trigonometric',['../group__math__invtrig.html',1,'Inverse trigonometric'],['../group__math__trig.html',1,'Trigonometric']]],
  ['tuning_20algorithms_24',['Tuning algorithms',['../intro-02.html#autotoc_md150',1,'']]],
  ['tuple_20of_20simd_20registers_25',['Tuple of SIMD registers',['../intro-03.html#autotoc_md152',1,'']]],
  ['tuples_26',['tuples',['../intro-03.html#autotoc_md153',1,'SIMD register of tuples'],['../intro-03.html',1,'Tuples']]],
  ['tutorials_27',['Tutorials',['../tutorials.html',1,'']]],
  ['two_5fsub_28',['two_sub',['../namespaceeve_abc88ded4203ae8d5d7698193ca58cc40.html#abc88ded4203ae8d5d7698193ca58cc40',1,'eve']]],
  ['type_29',['type',['../glossary_semantic.html#autotoc_md94',1,'Element type'],['../structeve_1_1underlying__type.html#autotoc_md78',1,'Helper type'],['../structeve_1_1as.html#a904ff0e88e1f435dc24505e3168b52f5',1,'eve::as::type']]],
  ['type_20traits_30',['Type traits',['../group__traits.html',1,'']]],
  ['type_20x_20cardinal_31',['SIMD registers as Type x Cardinal',['../design_rationale.html#rationale-simd',1,'']]],
  ['types_32',['types',['../concepteve_1_1arithmetic__scalar__value.html#autotoc_md10',1,'Example Types'],['../concepteve_1_1product__scalar__value.html#autotoc_md9',1,'Example Types'],['../concepteve_1_1logical__scalar__value.html#autotoc_md8',1,'Example Types'],['../concepteve_1_1plain__scalar__value.html#autotoc_md7',1,'Example Types'],['../concepteve_1_1logical__simd__value.html#autotoc_md11',1,'Example Types'],['../structeve_1_1abi.html#autotoc_md1',1,'Helper types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md4',1,'Helper types'],['../structeve_1_1element__type.html#autotoc_md76',1,'Helper types'],['../structeve_1_1common__compatible.html#autotoc_md73',1,'Helper types'],['../structeve_1_1abi.html#autotoc_md0',1,'Member types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md3',1,'Member types'],['../structeve_1_1element__type.html#autotoc_md75',1,'Member types'],['../structeve_1_1common__compatible.html#autotoc_md72',1,'Member types'],['../structeve_1_1cardinal.html#autotoc_md71',1,'Member types'],['../glossary_semantic.html#autotoc_md92',1,'Property of EVE types'],['../group__simd__types.html',1,'SIMD related types']]],
  ['types_20and_20helpers_33',['Architecture related Types and Helpers',['../group__arch.html',1,'']]],
  ['types_20management_34',['Structured Types Management',['../group__struct.html',1,'']]]
];
