var searchData=
[
  ['traits_0',['Traits',['https://jfalcou.github.io/kumi/group__traits.html',1,'Product Type Related Traits'],['https://jfalcou.github.io/kumi/group__record__traits.html',1,'Record Related Traits'],['https://jfalcou.github.io/kumi/group__tuple__traits.html',1,'Tuple Related Traits']]],
  ['traits_1',['Type traits',['../group__eve__traits.html',1,'']]],
  ['transformations_2',['Transformations',['https://jfalcou.github.io/kumi/group__transforms.html',1,'Product Type Transformations'],['https://jfalcou.github.io/kumi/group__record__transforms.html',1,'Record Type Specific Transformations'],['https://jfalcou.github.io/kumi/group__tuple__transforms.html',1,'Tuple Type Specific Transformations']]],
  ['trigonometric_3',['Trigonometric',['../group__eve__math__trig.html',1,'']]],
  ['trigonometric_4',['Inverse trigonometric',['../group__eve__math__invtrig.html',1,'']]],
  ['tuple_20related_20traits_5',['Tuple Related Traits',['https://jfalcou.github.io/kumi/group__tuple__traits.html',1,'']]],
  ['tuple_20type_20specific_20transformations_6',['Tuple Type Specific Transformations',['https://jfalcou.github.io/kumi/group__tuple__transforms.html',1,'']]],
  ['type_20algorithms_7',['Product Type Algorithms',['https://jfalcou.github.io/kumi/group__algorithm.html',1,'']]],
  ['type_20generalized_20reductions_8',['Product Type Generalized Reductions',['https://jfalcou.github.io/kumi/group__reductions.html',1,'']]],
  ['type_20generators_9',['Product Type Generators',['https://jfalcou.github.io/kumi/group__generators.html',1,'']]],
  ['type_20queries_10',['Product Type Queries',['https://jfalcou.github.io/kumi/group__queries.html',1,'']]],
  ['type_20related_20concepts_11',['Product Type Related Concepts',['https://jfalcou.github.io/kumi/group__concepts.html',1,'']]],
  ['type_20related_20traits_12',['Product Type Related Traits',['https://jfalcou.github.io/kumi/group__traits.html',1,'']]],
  ['type_20specific_20transformations_13',['Type Specific Transformations',['https://jfalcou.github.io/kumi/group__record__transforms.html',1,'Record Type Specific Transformations'],['https://jfalcou.github.io/kumi/group__tuple__transforms.html',1,'Tuple Type Specific Transformations']]],
  ['type_20traits_14',['Type traits',['../group__eve__traits.html',1,'']]],
  ['type_20transformations_15',['Product Type Transformations',['https://jfalcou.github.io/kumi/group__transforms.html',1,'']]],
  ['types_16',['Kumi Types',['https://jfalcou.github.io/kumi/group__types.html',1,'']]],
  ['types_17',['SIMD related types',['../group__eve__simd__types.html',1,'']]],
  ['types_20and_20associated_20functions_18',['Types and associated Functions',['https://jfalcou.github.io/kumi/group__tuple__related.html',1,'Product Types and associated Functions'],['https://jfalcou.github.io/kumi/group__record__related.html',1,'Record Types and associated Functions']]],
  ['types_20and_20function_19',['Helper Types and function',['https://jfalcou.github.io/kumi/group__functional.html',1,'']]],
  ['types_20and_20functions_20',['Types and Functions',['https://jfalcou.github.io/kumi/group__details.html',1,'Helper Types and Functions'],['https://jfalcou.github.io/kumi/group__utility.html',1,'Helper Types and Functions']]],
  ['types_20and_20helpers_21',['Architecture related Types and Helpers',['../group__eve__arch.html',1,'']]],
  ['types_20management_22',['Structured Types Management',['../group__eve__struct.html',1,'']]]
];
