var searchData=
[
  ['c_20specific_20terms_0',['C++ Specific Terms',['https://jfalcou.github.io/kumi/kumi_cpp_spec.html',1,'']]],
  ['callable_20function_20objects_20as_20main_20api_1',['Callable Function Objects as main API',['../design_rationale.html#rationale-callable',1,'']]],
  ['calls_2',['Masked Calls',['../group__eve__core__compress_ga8e545371fd605df1555e4cd0b2f62374.html#autotoc_md17',1,'']]],
  ['cardinal_3',['Cardinal',['../glossary_semantic.html#autotoc_md64',1,'Cardinal'],['../design_rationale.html#rationale-simd',1,'SIMD registers as Type x Cardinal']]],
  ['change_20log_4',['Change Log',['https://jfalcou.github.io/kumi/kumi_changelog.html',1,'Change Log'],['../changelog.html',1,'Change Log']]],
  ['changed_5',['Changed',['../changelog.html#autotoc_md33',1,'What&apos;s Changed'],['../changelog.html#autotoc_md42',1,'What&apos;s Changed'],['../changelog.html#autotoc_md45',1,'What&apos;s Changed'],['../changelog.html#autotoc_md48',1,'What&apos;s Changed']]],
  ['check_20for_20any_6',['check for any',['../group__eve__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md18',1,'Should you check for any?'],['../group__eve__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md20',1,'Should you check for any?']]],
  ['classification_7',['Operations Classification',['../glossary_semantic.html#autotoc_md67',1,'']]],
  ['cmake_8',['Use with CMake',['../setup.html#autotoc_md85',1,'']]],
  ['cmake_20setup_9',['CMake setup',['../dev_cmake.html#autotoc_md60',1,'']]],
  ['code_10',['Interaction with native code.',['../inter-with-native.html',1,'']]],
  ['compilation_11',['Compilation',['../setup.html#autotoc_md82',1,'']]],
  ['compilers_20support_20fixes_12',['Architectures/Compilers Support &amp;amp; Fixes',['../changelog.html#autotoc_md35',1,'']]],
  ['compiling_20and_20using_20dynamic_20kernels_13',['Compiling and Using Dynamic Kernels',['../multiarch.html#autotoc_md115',1,'']]],
  ['compiling_20eve_20random_20tests_14',['Compiling EVE Random Tests',['../dev_cmake.html#autotoc_md62',1,'']]],
  ['compiling_20eve_20unit_20tests_15',['Compiling EVE Unit Tests',['../dev_cmake.html#autotoc_md61',1,'']]],
  ['components_16',['Basic Components',['../algo_rationale.html#autotoc_md53',1,'']]],
  ['components_20semantic_17',['Components Semantic',['../glossary_semantic.html',1,'']]],
  ['concepts_18',['concepts',['../algo_rationale.html#autotoc_md56',1,'General concepts'],['../algo_rationale.html#autotoc_md57',1,'Relaxed concepts']]],
  ['conclusion_19',['Conclusion',['../conditional.html#autotoc_md92',1,'Conclusion'],['../intro-01.html#autotoc_md98',1,'Conclusion'],['../intro-02.html#autotoc_md102',1,'Conclusion'],['../intro-03.html#autotoc_md105',1,'Conclusion'],['../intro-04.html#autotoc_md109',1,'Conclusion'],['../intro-05.html#autotoc_md110',1,'Conclusion'],['../multiarch.html#autotoc_md116',1,'Conclusion']]],
  ['conditional_20expressions_20',['Conditional Expressions',['../conditional.html#autotoc_md89',1,'']]],
  ['conditional_20function_20syntax_21',['Conditional Function Syntax',['../conditional.html#autotoc_md88',1,'']]],
  ['conditional_20operations_22',['Conditional operations',['../conditional.html',1,'']]],
  ['constant_20functions_23',['Constant Functions',['../glossary_semantic.html#glossary_constant',1,'']]],
  ['context_20sensitive_20mask_24',['Context-sensitive mask',['../conditional.html#autotoc_md91',1,'']]],
  ['contributors_25',['Contributors',['../changelog.html#autotoc_md43',1,'New Contributors'],['../changelog.html#autotoc_md46',1,'New Contributors']]],
  ['cpm_26',['CPM',['../setup.html#autotoc_md75',1,'']]],
  ['creating_20simd_20aware_20udt_27',['Creating SIMD-aware UDT',['../intro-04.html#autotoc_md107',1,'']]],
  ['customization_28',['Customization',['../algo_rationale.html#autotoc_md58',1,'']]],
  ['customization_20via_20higher_20order_20decorator_29',['Function customization via higher-order decorator',['../design_rationale.html#rationale-decorator',1,'']]]
];
