var searchData=
[
  ['s_20changed_0',['s Changed',['../changelog.html#autotoc_md37',1,'What&apos;s Changed'],['../changelog.html#autotoc_md46',1,'What&apos;s Changed'],['../changelog.html#autotoc_md49',1,'What&apos;s Changed'],['../changelog.html#autotoc_md52',1,'What&apos;s Changed']]],
  ['scalar_20to_20simd_20using_20eve_3a_3awide_1',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md99',1,'']]],
  ['scaling_2',['Frequency Scaling.',['../freqscale.html',1,'']]],
  ['selection_3',['Selection',['../conditional.html#autotoc_md91',1,'Explicit Selection'],['../setup.html#autotoc_md87',1,'Instruction Set Selection']]],
  ['semantic_4',['Semantic',['../glossary_semantic.html',1,'Components Semantic'],['../glossary_semantic.html#autotoc_md73',1,'Function Semantic']]],
  ['sensitive_20mask_5',['Context-sensitive mask',['../conditional.html#autotoc_md95',1,'']]],
  ['set_20selection_6',['Instruction Set Selection',['../setup.html#autotoc_md87',1,'']]],
  ['setting_20up_20the_20library_7',['Setting up the Library',['../setup.html#autotoc_md83',1,'']]],
  ['setup_8',['setup',['../dev_cmake.html#autotoc_md64',1,'CMake setup'],['../dev_environment.html#dev_docker_setup',1,'Docker setup']]],
  ['should_20you_20check_20for_20any_9',['Should you check for any',['../group__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md21',1,'Should you check for any?'],['../group__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md23',1,'Should you check for any?']]],
  ['simd_20algorithms_10',['SIMD Algorithms',['../algo_rationale.html',1,'SIMD Algorithms'],['../intro-02.html#autotoc_md104',1,'Toward SIMD Algorithms']]],
  ['simd_20aware_20udt_11',['Creating SIMD-aware UDT',['../intro-04.html#autotoc_md111',1,'']]],
  ['simd_20processing_12',['Adapting UDT to SIMD processing',['../intro-04.html#autotoc_md110',1,'']]],
  ['simd_20register_20of_20tuples_13',['SIMD register of tuples',['../intro-03.html#autotoc_md108',1,'']]],
  ['simd_20registers_14',['Tuple of SIMD registers',['../intro-03.html#autotoc_md107',1,'']]],
  ['simd_20registers_20as_20type_20x_20cardinal_15',['SIMD registers as Type x Cardinal',['../design_rationale.html#rationale-simd',1,'']]],
  ['simd_20using_20eve_3a_3awide_16',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md99',1,'']]],
  ['sizes_17',['What about non-native sizes?',['../inter-with-native.html#autotoc_md97',1,'']]],
  ['solving_20quadratic_20equations_18',['Solving quadratic equations',['../intro-05.html',1,'']]],
  ['source_19',['Installation from Source',['../setup.html#autotoc_md82',1,'']]],
  ['source_20',['Retrieving the source',['../setup.html#autotoc_md77',1,'']]],
  ['spack_21',['SPACK',['../setup.html#autotoc_md80',1,'']]],
  ['start_22',['Installation &amp;amp; Quick Start',['../setup.html',1,'']]],
  ['static_20to_20dynamic_20dispatch_23',['From static to dynamic dispatch',['../multiarch.html#autotoc_md116',1,'']]],
  ['storage_20and_20processing_24',['Storage and Processing',['../intro-04.html#autotoc_md112',1,'']]],
  ['structures_25',['Data Structures',['../intro-04.html',1,'']]],
  ['support_26',['Masked operations support',['../design_rationale.html#rationale-mask',1,'']]],
  ['support_20fixes_27',['Architectures/Compilers Support &amp;amp; Fixes',['../changelog.html#autotoc_md39',1,'']]],
  ['sve_28',['The One Big News for this release: SVE',['../changelog.html#autotoc_md40',1,'']]],
  ['syntax_29',['Conditional Function Syntax',['../conditional.html#autotoc_md92',1,'']]]
];
