var searchData=
[
  ['targets_0',['Handling Multiple Architecture Targets',['../multiarch.html',1,'']]],
  ['template_1',['template',['../group__eve__arch_gab707570aa2d35678c5cd5c686a994d57.html#autotoc_md2',1,'Helper variable template'],['../structeve_1_1fundamental__cardinal.html#autotoc_md5',1,'Helper variable template'],['../structeve_1_1supports__ordering.html#autotoc_md30',1,'Helper variable template']]],
  ['terms_2',['C++ Specific Terms',['https://jfalcou.github.io/kumi/cpp_spec.html',1,'']]],
  ['testing_3',['Building for Testing',['../dev_cmake.html',1,'']]],
  ['tests_4',['Tests',['../dev_cmake.html#autotoc_md62',1,'Compiling EVE Random Tests'],['../dev_cmake.html#autotoc_md61',1,'Compiling EVE Unit Tests']]],
  ['the_200_20and_201_20of_20types_5',['The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)',['https://jfalcou.github.io/kumi/identity.html',1,'']]],
  ['the_20documentation_6',['Building the Documentation',['../setup.html#autotoc_md80',1,'']]],
  ['the_20dynamic_20function_20hub_7',['Writing the dynamic function hub',['../multiarch.html#autotoc_md114',1,'']]],
  ['the_20expressive_20vector_20engine_8',['The Expressive Vector Engine',['../index.html',1,'']]],
  ['the_20identity_20elements_20the_200_20and_201_20of_20types_9',['The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)',['https://jfalcou.github.io/kumi/identity.html',1,'']]],
  ['the_20issue_10',['The Issue',['../multiarch.html#autotoc_md111',1,'']]],
  ['the_20kernel_11',['Writing the kernel',['../multiarch.html#autotoc_md113',1,'']]],
  ['the_20library_12',['Setting up the Library',['../setup.html#autotoc_md79',1,'']]],
  ['the_20library_13',['Using the library',['../setup.html#autotoc_md81',1,'']]],
  ['the_20one_20big_20news_20for_20this_20release_3a_20sve_14',['The One Big News for this release: SVE',['../changelog.html#autotoc_md36',1,'']]],
  ['the_20source_15',['Retrieving the source',['../setup.html#autotoc_md73',1,'']]],
  ['theoretic_20foundations_16',['Type Theoretic Foundations',['https://jfalcou.github.io/kumi/introduction.html',1,'']]],
  ['there_20is_20a_20match_17',['there is a match',['../group__eve__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md19',1,'What if I know there is a match?'],['../group__eve__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md21',1,'What if I know there is a match?']]],
  ['this_20release_3a_20sve_18',['The One Big News for this release: SVE',['../changelog.html#autotoc_md36',1,'']]],
  ['to_20dynamic_20dispatch_19',['From static to dynamic dispatch',['../multiarch.html#autotoc_md112',1,'']]],
  ['to_20simd_20processing_20',['Adapting UDT to SIMD processing',['../intro-04.html#autotoc_md106',1,'']]],
  ['to_20simd_20using_20eve_3a_3awide_21',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md95',1,'']]],
  ['toward_20simd_20algorithms_22',['Toward SIMD Algorithms',['../intro-02.html#autotoc_md100',1,'']]],
  ['traits_23',['traits',['../glossary_semantic.html#autotoc_md66',1,'ABI traits'],['../algo_rationale.html#autotoc_md59',1,'Algorithms traits']]],
  ['trying_20eve_20without_20building_20it_24',['Trying EVE without building it',['../dev_environment.html#dev_docker_eve',1,'']]],
  ['tuning_20algorithms_25',['Tuning algorithms',['../intro-02.html#autotoc_md101',1,'']]],
  ['tuple_20of_20simd_20registers_26',['Tuple of SIMD registers',['../intro-03.html#autotoc_md103',1,'']]],
  ['tuples_27',['Tuples',['../intro-03.html',1,'']]],
  ['tuples_28',['SIMD register of tuples',['../intro-03.html#autotoc_md104',1,'']]],
  ['type_29',['type',['../glossary_semantic.html#autotoc_md65',1,'Element type'],['../structeve_1_1underlying__type.html#autotoc_md31',1,'Helper type']]],
  ['type_20theoretic_20foundations_30',['Type Theoretic Foundations',['https://jfalcou.github.io/kumi/introduction.html',1,'']]],
  ['type_20x_20cardinal_31',['SIMD registers as Type x Cardinal',['../design_rationale.html#rationale-simd',1,'']]],
  ['types_32',['Types',['../concepteve_1_1translatable__ptr.html#autotoc_md7',1,'Example Types'],['../concepteve_1_1plain__scalar__value.html#autotoc_md8',1,'Example Types'],['../concepteve_1_1logical__scalar__value.html#autotoc_md9',1,'Example Types'],['../concepteve_1_1product__scalar__value.html#autotoc_md10',1,'Example Types'],['../concepteve_1_1arithmetic__scalar__value.html#autotoc_md11',1,'Example Types'],['../concepteve_1_1logical__simd__value.html#autotoc_md12',1,'Example Types'],['../concepteve_1_1has__plain__translation.html#autotoc_md13',1,'Example Types'],['https://jfalcou.github.io/kumi/product.html',1,'Product Types'],['https://jfalcou.github.io/kumi/identity.html',1,'The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)']]],
  ['types_33',['types',['../structeve_1_1abi.html#autotoc_md1',1,'Helper types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md4',1,'Helper types'],['../structeve_1_1common__compatible.html#autotoc_md26',1,'Helper types'],['../structeve_1_1element__type.html#autotoc_md29',1,'Helper types'],['../structeve_1_1abi.html#autotoc_md0',1,'Member types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md3',1,'Member types'],['../structeve_1_1cardinal.html#autotoc_md24',1,'Member types'],['../structeve_1_1common__compatible.html#autotoc_md25',1,'Member types'],['../structeve_1_1element__type.html#autotoc_md28',1,'Member types'],['../glossary_semantic.html#autotoc_md63',1,'Property of EVE types']]]
];
