var searchData=
[
  ['callable_20function_20objects_20as_20main_20api_0',['Callable Function Objects as main API',['../design_rationale.html#rationale-callable',1,'']]],
  ['calls_1',['Masked Calls',['../group__core__compress_ga8e545371fd605df1555e4cd0b2f62374.html#autotoc_md17',1,'']]],
  ['cardinal_2',['Cardinal',['../glossary_semantic.html#autotoc_md68',1,'Cardinal'],['../design_rationale.html#rationale-simd',1,'SIMD registers as Type x Cardinal']]],
  ['change_20log_3',['Change Log',['../changelog.html',1,'']]],
  ['changed_4',['Changed',['../changelog.html#autotoc_md37',1,'What&apos;s Changed'],['../changelog.html#autotoc_md46',1,'What&apos;s Changed'],['../changelog.html#autotoc_md49',1,'What&apos;s Changed'],['../changelog.html#autotoc_md52',1,'What&apos;s Changed']]],
  ['check_20for_20any_5',['check for any',['../group__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md21',1,'Should you check for any?'],['../group__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md23',1,'Should you check for any?']]],
  ['classification_6',['Operations Classification',['../glossary_semantic.html#autotoc_md71',1,'']]],
  ['cmake_7',['Use with CMake',['../setup.html#autotoc_md89',1,'']]],
  ['cmake_20setup_8',['CMake setup',['../dev_cmake.html#autotoc_md64',1,'']]],
  ['code_9',['Interaction with native code.',['../inter-with-native.html',1,'']]],
  ['compilation_10',['Compilation',['../setup.html#autotoc_md86',1,'']]],
  ['compilers_20support_20fixes_11',['Architectures/Compilers Support &amp;amp; Fixes',['../changelog.html#autotoc_md39',1,'']]],
  ['compiling_20and_20using_20dynamic_20kernels_12',['Compiling and Using Dynamic Kernels',['../multiarch.html#autotoc_md119',1,'']]],
  ['compiling_20eve_20random_20tests_13',['Compiling EVE Random Tests',['../dev_cmake.html#autotoc_md66',1,'']]],
  ['compiling_20eve_20unit_20tests_14',['Compiling EVE Unit Tests',['../dev_cmake.html#autotoc_md65',1,'']]],
  ['components_15',['Basic Components',['../algo_rationale.html#autotoc_md57',1,'']]],
  ['components_20semantic_16',['Components Semantic',['../glossary_semantic.html',1,'']]],
  ['concepts_17',['concepts',['../algo_rationale.html#autotoc_md60',1,'General concepts'],['../algo_rationale.html#autotoc_md61',1,'Relaxed concepts']]],
  ['conclusion_18',['Conclusion',['../conditional.html#autotoc_md96',1,'Conclusion'],['../intro-01.html#autotoc_md102',1,'Conclusion'],['../intro-02.html#autotoc_md106',1,'Conclusion'],['../intro-03.html#autotoc_md109',1,'Conclusion'],['../intro-04.html#autotoc_md113',1,'Conclusion'],['../intro-05.html#autotoc_md114',1,'Conclusion'],['../multiarch.html#autotoc_md120',1,'Conclusion']]],
  ['conditional_20expressions_19',['Conditional Expressions',['../conditional.html#autotoc_md93',1,'']]],
  ['conditional_20function_20syntax_20',['Conditional Function Syntax',['../conditional.html#autotoc_md92',1,'']]],
  ['conditional_20operations_21',['Conditional operations',['../conditional.html',1,'']]],
  ['constant_20functions_22',['Constant Functions',['../glossary_semantic.html#glossary_constant',1,'']]],
  ['context_20sensitive_20mask_23',['Context-sensitive mask',['../conditional.html#autotoc_md95',1,'']]],
  ['contributors_24',['Contributors',['../changelog.html#autotoc_md47',1,'New Contributors'],['../changelog.html#autotoc_md50',1,'New Contributors']]],
  ['cpm_25',['CPM',['../setup.html#autotoc_md79',1,'']]],
  ['creating_20simd_20aware_20udt_26',['Creating SIMD-aware UDT',['../intro-04.html#autotoc_md111',1,'']]],
  ['customization_27',['Customization',['../algo_rationale.html#autotoc_md62',1,'']]],
  ['customization_20via_20higher_20order_20decorator_28',['Function customization via higher-order decorator',['../design_rationale.html#rationale-decorator',1,'']]]
];
