var searchData=
[
  ['s_20changed_0',['s Changed',['../changelog.html#autotoc_md33',1,'What&apos;s Changed'],['../changelog.html#autotoc_md42',1,'What&apos;s Changed'],['../changelog.html#autotoc_md45',1,'What&apos;s Changed'],['../changelog.html#autotoc_md48',1,'What&apos;s Changed']]],
  ['scalar_20to_20simd_20using_20eve_3a_3awide_1',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md95',1,'']]],
  ['scaling_2',['Frequency Scaling.',['../freqscale.html',1,'']]],
  ['selection_3',['Selection',['../conditional.html#autotoc_md87',1,'Explicit Selection'],['../setup.html#autotoc_md83',1,'Instruction Set Selection']]],
  ['semantic_4',['Semantic',['../glossary_semantic.html',1,'Components Semantic'],['../glossary_semantic.html#autotoc_md69',1,'Function Semantic']]],
  ['sensitive_20mask_5',['Context-sensitive mask',['../conditional.html#autotoc_md91',1,'']]],
  ['set_20selection_6',['Instruction Set Selection',['../setup.html#autotoc_md83',1,'']]],
  ['setting_20up_20the_20library_7',['Setting up the Library',['../setup.html#autotoc_md79',1,'']]],
  ['setup_8',['Setup',['https://jfalcou.github.io/kumi/kumi_setup.html',1,'']]],
  ['setup_9',['setup',['../dev_cmake.html#autotoc_md60',1,'CMake setup'],['../dev_environment.html#dev_docker_setup',1,'Docker setup']]],
  ['should_20you_20check_20for_20any_10',['Should you check for any',['../group__eve__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md18',1,'Should you check for any?'],['../group__eve__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md20',1,'Should you check for any?']]],
  ['simd_20algorithms_11',['SIMD Algorithms',['../algo_rationale.html',1,'SIMD Algorithms'],['../intro-02.html#autotoc_md100',1,'Toward SIMD Algorithms']]],
  ['simd_20aware_20udt_12',['Creating SIMD-aware UDT',['../intro-04.html#autotoc_md107',1,'']]],
  ['simd_20processing_13',['Adapting UDT to SIMD processing',['../intro-04.html#autotoc_md106',1,'']]],
  ['simd_20register_20of_20tuples_14',['SIMD register of tuples',['../intro-03.html#autotoc_md104',1,'']]],
  ['simd_20registers_15',['Tuple of SIMD registers',['../intro-03.html#autotoc_md103',1,'']]],
  ['simd_20registers_20as_20type_20x_20cardinal_16',['SIMD registers as Type x Cardinal',['../design_rationale.html#rationale-simd',1,'']]],
  ['simd_20using_20eve_3a_3awide_17',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md95',1,'']]],
  ['sizes_18',['What about non-native sizes?',['../inter-with-native.html#autotoc_md93',1,'']]],
  ['solving_20quadratic_20equations_19',['Solving quadratic equations',['../intro-05.html',1,'']]],
  ['source_20',['Installation from Source',['../setup.html#autotoc_md78',1,'']]],
  ['source_21',['Retrieving the source',['../setup.html#autotoc_md73',1,'']]],
  ['spack_22',['SPACK',['../setup.html#autotoc_md76',1,'']]],
  ['specific_20terms_23',['C++ Specific Terms',['https://jfalcou.github.io/kumi/kumi_cpp_spec.html',1,'']]],
  ['start_24',['Installation &amp;amp; Quick Start',['../setup.html',1,'']]],
  ['static_20to_20dynamic_20dispatch_25',['From static to dynamic dispatch',['../multiarch.html#autotoc_md112',1,'']]],
  ['storage_20and_20processing_26',['Storage and Processing',['../intro-04.html#autotoc_md108',1,'']]],
  ['structures_27',['Data Structures',['../intro-04.html',1,'']]],
  ['support_28',['Masked operations support',['../design_rationale.html#rationale-mask',1,'']]],
  ['support_20fixes_29',['Architectures/Compilers Support &amp;amp; Fixes',['../changelog.html#autotoc_md35',1,'']]],
  ['sve_30',['The One Big News for this release: SVE',['../changelog.html#autotoc_md36',1,'']]],
  ['syntax_31',['Conditional Function Syntax',['../conditional.html#autotoc_md88',1,'']]]
];
