var searchData=
[
  ['targets_0',['Handling Multiple Architecture Targets',['../multiarch.html',1,'']]],
  ['template_1',['template',['../group__arch_gab707570aa2d35678c5cd5c686a994d57.html#autotoc_md2',1,'Helper variable template'],['../structeve_1_1fundamental__cardinal.html#autotoc_md5',1,'Helper variable template'],['../structeve_1_1supports__ordering.html#autotoc_md34',1,'Helper variable template']]],
  ['testing_2',['Building for Testing',['../dev_cmake.html',1,'']]],
  ['tests_3',['Tests',['../dev_cmake.html#autotoc_md66',1,'Compiling EVE Random Tests'],['../dev_cmake.html#autotoc_md65',1,'Compiling EVE Unit Tests']]],
  ['the_20documentation_4',['Building the Documentation',['../setup.html#autotoc_md84',1,'']]],
  ['the_20dynamic_20function_20hub_5',['Writing the dynamic function hub',['../multiarch.html#autotoc_md118',1,'']]],
  ['the_20expressive_20vector_20engine_6',['The Expressive Vector Engine',['../index.html',1,'']]],
  ['the_20issue_7',['The Issue',['../multiarch.html#autotoc_md115',1,'']]],
  ['the_20kernel_8',['Writing the kernel',['../multiarch.html#autotoc_md117',1,'']]],
  ['the_20library_9',['Setting up the Library',['../setup.html#autotoc_md83',1,'']]],
  ['the_20library_10',['Using the library',['../setup.html#autotoc_md85',1,'']]],
  ['the_20one_20big_20news_20for_20this_20release_3a_20sve_11',['The One Big News for this release: SVE',['../changelog.html#autotoc_md40',1,'']]],
  ['the_20source_12',['Retrieving the source',['../setup.html#autotoc_md77',1,'']]],
  ['there_20is_20a_20match_13',['there is a match',['../group__core__reduction_ga146ea89681f9d926afcc7b3bf968f40d.html#autotoc_md22',1,'What if I know there is a match?'],['../group__core__reduction_gabc10fff649535870a897cef2a1e1673e.html#autotoc_md24',1,'What if I know there is a match?']]],
  ['this_20release_3a_20sve_14',['The One Big News for this release: SVE',['../changelog.html#autotoc_md40',1,'']]],
  ['to_20dynamic_20dispatch_15',['From static to dynamic dispatch',['../multiarch.html#autotoc_md116',1,'']]],
  ['to_20simd_20processing_16',['Adapting UDT to SIMD processing',['../intro-04.html#autotoc_md110',1,'']]],
  ['to_20simd_20using_20eve_3a_3awide_17',['From scalar to SIMD using eve::wide',['../intro-01.html#autotoc_md99',1,'']]],
  ['toward_20simd_20algorithms_18',['Toward SIMD Algorithms',['../intro-02.html#autotoc_md104',1,'']]],
  ['traits_19',['traits',['../glossary_semantic.html#autotoc_md70',1,'ABI traits'],['../algo_rationale.html#autotoc_md63',1,'Algorithms traits']]],
  ['tuning_20algorithms_20',['Tuning algorithms',['../intro-02.html#autotoc_md105',1,'']]],
  ['tuple_20of_20simd_20registers_21',['Tuple of SIMD registers',['../intro-03.html#autotoc_md107',1,'']]],
  ['tuples_22',['Tuples',['../intro-03.html',1,'']]],
  ['tuples_23',['SIMD register of tuples',['../intro-03.html#autotoc_md108',1,'']]],
  ['type_24',['type',['../glossary_semantic.html#autotoc_md69',1,'Element type'],['../structeve_1_1underlying__type.html#autotoc_md35',1,'Helper type']]],
  ['type_20x_20cardinal_25',['SIMD registers as Type x Cardinal',['../design_rationale.html#rationale-simd',1,'']]],
  ['types_26',['Types',['../concepteve_1_1translatable__ptr.html#autotoc_md7',1,'Example Types'],['../concepteve_1_1plain__scalar__value.html#autotoc_md8',1,'Example Types'],['../concepteve_1_1logical__scalar__value.html#autotoc_md9',1,'Example Types'],['../concepteve_1_1product__scalar__value.html#autotoc_md10',1,'Example Types'],['../concepteve_1_1arithmetic__scalar__value.html#autotoc_md11',1,'Example Types'],['../concepteve_1_1logical__simd__value.html#autotoc_md12',1,'Example Types'],['../concepteve_1_1has__plain__translation.html#autotoc_md13',1,'Example Types']]],
  ['types_27',['types',['../structeve_1_1abi.html#autotoc_md1',1,'Helper types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md4',1,'Helper types'],['../structeve_1_1common__compatible.html#autotoc_md30',1,'Helper types'],['../structeve_1_1element__type.html#autotoc_md33',1,'Helper types'],['../structeve_1_1abi.html#autotoc_md0',1,'Member types'],['../structeve_1_1fundamental__cardinal.html#autotoc_md3',1,'Member types'],['../structeve_1_1cardinal.html#autotoc_md28',1,'Member types'],['../structeve_1_1common__compatible.html#autotoc_md29',1,'Member types'],['../structeve_1_1element__type.html#autotoc_md32',1,'Member types'],['../glossary_semantic.html#autotoc_md67',1,'Property of EVE types']]]
];
