# action.yml
name: 'Clone and Build Tests'
description: 'Clone and build a given repository'
inputs:
  options:  # compiler options
    description: 'Compiler options'
    required: false
    default: ''
  cmake-options:  # CMake options
    description: 'CMake options'
    required: false
    default: ''
  status:  # How much of the test we shoudl run
    description: 'Completion Status'
    required: false
    default: '1'
runs:
  using: "composite"
  steps:
    - run: .github/actions/run_tests/run.sh ${{ inputs.options }} ${{ inputs.cmake-options }} ${{ inputs.status }}
      shell: bash
