# action.yml
name: 'Clone and Build Tests'
description: 'Clone and build a given repository'
inputs:
  repository:  # repository to clone
    description: 'Repository to clone'
    required: true
    default: ${{ github.repository }}
  branch:  # branch to select
    description: 'Branch to build'
    required: true
    default: ${{ github.ref }}
  options:  # compiler options
    description: 'Compiler options'
    required: false
    default: ''
  cmake-options:  # CMake options
    description: 'CMake options'
    required: false
    default: ''
  status:  # How much of the test we shoudl run
    description: 'Completion Status'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.options }}
    - ${{ inputs.cmake-options }}
    - ${{ inputs.status }}
