//==================================================================================================
/**
  EVE - Expressive Vector Engine
  Copyright : EVE Contributors & Maintainers
  SPDX-License-Identifier: MIT
**/
//==================================================================================================
#pragma once

#include <eve/module/math/diff/acosd.hpp>
#include <eve/module/math/diff/acosh.hpp>
#include <eve/module/math/diff/acos.hpp>
#include <eve/module/math/diff/acospi.hpp>
#include <eve/module/math/diff/acotd.hpp>
#include <eve/module/math/diff/acoth.hpp>
#include <eve/module/math/diff/acot.hpp>
#include <eve/module/math/diff/acotpi.hpp>
#include <eve/module/math/diff/acscd.hpp>
#include <eve/module/math/diff/acsch.hpp>
#include <eve/module/math/diff/acsc.hpp>
#include <eve/module/math/diff/acscpi.hpp>
#include <eve/module/math/diff/arg.hpp>
#include <eve/module/math/diff/asecd.hpp>
#include <eve/module/math/diff/asech.hpp>
#include <eve/module/math/diff/asec.hpp>
#include <eve/module/math/diff/asecpi.hpp>
#include <eve/module/math/diff/asind.hpp>
#include <eve/module/math/diff/asinh.hpp>
#include <eve/module/math/diff/asin.hpp>
#include <eve/module/math/diff/asinpi.hpp>
#include <eve/module/math/diff/atan2d.hpp>
#include <eve/module/math/diff/atan2.hpp>
#include <eve/module/math/diff/atan2pi.hpp>
#include <eve/module/math/diff/atand.hpp>
#include <eve/module/math/diff/atanh.hpp>
#include <eve/module/math/diff/atan.hpp>
#include <eve/module/math/diff/atanpi.hpp>
#include <eve/module/math/diff/cbrt.hpp>
#include <eve/module/math/diff/cosd.hpp>
#include <eve/module/math/diff/cosh.hpp>
#include <eve/module/math/diff/cos.hpp>
#include <eve/module/math/diff/cospi.hpp>
#include <eve/module/math/diff/cotd.hpp>
#include <eve/module/math/diff/coth.hpp>
#include <eve/module/math/diff/cot.hpp>
#include <eve/module/math/diff/cotpi.hpp>
#include <eve/module/math/diff/csc.hpp>
#include <eve/module/math/diff/cscd.hpp>
#include <eve/module/math/diff/csch.hpp>
#include <eve/module/math/diff/cscpi.hpp>
#include <eve/module/math/diff/deginrad.hpp>
#include <eve/module/math/diff/exp10.hpp>
#include <eve/module/math/diff/exp2.hpp>
#include <eve/module/math/diff/exp.hpp>
#include <eve/module/math/diff/expm1.hpp>
#include <eve/module/math/diff/expx2.hpp>
#include <eve/module/math/diff/gd.hpp>
#include <eve/module/math/diff/geommean.hpp>
#include <eve/module/math/diff/hypot.hpp>
#include <eve/module/math/diff/invgd.hpp>
#include <eve/module/math/diff/log10.hpp>
#include <eve/module/math/diff/log1p.hpp>
#include <eve/module/math/diff/log2.hpp>
#include <eve/module/math/diff/log_abs.hpp>
#include <eve/module/math/diff/log.hpp>
#include <eve/module/math/diff/logspace_add.hpp>
#include <eve/module/math/diff/logspace_sub.hpp>
#include <eve/module/math/diff/lpnorm.hpp>
#include <eve/module/math/diff/nthroot.hpp>
#include <eve/module/math/diff/pow1p.hpp>
#include <eve/module/math/diff/pow_abs.hpp>
#include <eve/module/math/diff/pow.hpp>
#include <eve/module/math/diff/powm1.hpp>
#include <eve/module/math/diff/radindeg.hpp>
#include <eve/module/math/diff/radinpi.hpp>
#include <eve/module/math/diff/secd.hpp>
#include <eve/module/math/diff/sech.hpp>
#include <eve/module/math/diff/sec.hpp>
#include <eve/module/math/diff/secpi.hpp>
#include <eve/module/math/diff/sinc.hpp>
#include <eve/module/math/diff/sincos.hpp>
#include <eve/module/math/diff/sindcosd.hpp>
#include <eve/module/math/diff/sind.hpp>
#include <eve/module/math/diff/sinhc.hpp>
#include <eve/module/math/diff/sinhcosh.hpp>
#include <eve/module/math/diff/sinh.hpp>
#include <eve/module/math/diff/sin.hpp>
#include <eve/module/math/diff/sinpic.hpp>
#include <eve/module/math/diff/sinpicospi.hpp>
#include <eve/module/math/diff/sinpi.hpp>
#include <eve/module/math/diff/tand.hpp>
#include <eve/module/math/diff/tanh.hpp>
#include <eve/module/math/diff/tan.hpp>
#include <eve/module/math/diff/tanpi.hpp>
