# action.yml
name: 'Clone and Build Tests'
description: 'Clone and build a given repository'
inputs:
  options:  # compiler options
    description: 'Compiler options'
    required: false
    default: ''
  cmake-options:  # CMake options
    description: 'CMake options'
    required: false
    default: ''
  status:  # How much of the test we should run
    description: 'Completion Status'
    required: false
    default: '1'
  cpu:  # How much CPU do we use
    description: 'CPU Count'
    required: false
    default: '8'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.options }}
    - ${{ inputs.cmake-options }}
    - ${{ inputs.status }}
    - ${{ inputs.cpu }}
