//==================================================================================================
/**
  EVE - Expressive Vector Engine
  Copyright 2020 Jean-Thierry LAPRESTE

  Licensed under the MIT License <http://opensource.org/licenses/MIT>.
  SPDX-License-Identifier: MIT
**/
//==================================================================================================
#pragma once
// **=======================================================
// helper file to include all arithmetic functions
#include <eve/function/abs.hpp>
#include <eve/function/add.hpp>
#include <eve/function/arg.hpp>
#include <eve/function/average.hpp>
#include <eve/function/bitofsign.hpp>
#include <eve/function/cbrt.hpp>
#include <eve/function/ceil.hpp>
#include <eve/function/clamp.hpp>
#include <eve/function/conj.hpp>
#include <eve/function/convert.hpp>
#include <eve/function/copysign.hpp>
#include <eve/function/countl_one.hpp>
#include <eve/function/countl_zero.hpp>
#include <eve/function/countr_one.hpp>
#include <eve/function/countr_zero.hpp>
#include <eve/function/dec.hpp>
#include <eve/function/dist.hpp>
#include <eve/function/div.hpp>
#include <eve/function/eps.hpp>
#include <eve/function/exponent.hpp>
#include <eve/function/extract.hpp>
#include <eve/function/fdim.hpp>
#include <eve/function/firstbitset.hpp>
#include <eve/function/firstbitunset.hpp>
#include <eve/function/floor.hpp>
#include <eve/function/fma.hpp>
#include <eve/function/fms.hpp>
#include <eve/function/fnma.hpp>
#include <eve/function/fnms.hpp>
#include <eve/function/frac.hpp>
#include <eve/function/frexp.hpp>
#include <eve/function/gcd.hpp>
#include <eve/function/has_single_bit.hpp>
#include <eve/function/hypot.hpp>
#include <eve/function/iceil.hpp>
#include <eve/function/ifloor.hpp>
#include <eve/function/ifrexp.hpp>
#include <eve/function/inc.hpp>
#include <eve/function/inearest.hpp>
#include <eve/function/iround.hpp>
#include <eve/function/itrunc.hpp>
#include <eve/function/lcm.hpp>
#include <eve/function/ldexp.hpp>
#include <eve/function/lerp.hpp>
#include <eve/function/manhattan.hpp>
#include <eve/function/mantissa.hpp>
#include <eve/function/max.hpp>
#include <eve/function/maximum.hpp>
#include <eve/function/maxmag.hpp>
#include <eve/function/min.hpp>
#include <eve/function/minimum.hpp>
#include <eve/function/minmag.hpp>
#include <eve/function/minus.hpp>
#include <eve/function/modf.hpp>
#include <eve/function/mul.hpp>
#include <eve/function/nb_values.hpp>
#include <eve/function/nearest.hpp>
#include <eve/function/negate.hpp>
#include <eve/function/negatenz.hpp>
#include <eve/function/nextafter.hpp>
#include <eve/function/next.hpp>
#include <eve/function/oneminus.hpp>
#include <eve/function/plus.hpp>
#include <eve/function/popcount.hpp>
#include <eve/function/predicates.hpp>
#include <eve/function/prev.hpp>
#include <eve/function/quadrant.hpp>
#include <eve/function/rec.hpp>
///#include <eve/function/reldist.hpp>
#include <eve/function/rem.hpp>
#include <eve/function/rotl.hpp>
#include <eve/function/rotr.hpp>
#include <eve/function/round.hpp>
#include <eve/function/rshl.hpp>
#include <eve/function/rshr.hpp>
#include <eve/function/rsqrt.hpp>
#include <eve/function/saturated.hpp>
#include <eve/function/saturate.hpp>
#include <eve/function/shl.hpp>
#include <eve/function/shr.hpp>
#include <eve/function/sign.hpp>
#include <eve/function/signnz.hpp>
#include <eve/function/sqr_abs.hpp>
#include <eve/function/sqr.hpp>
#include <eve/function/sqrt.hpp>
#include <eve/function/sub.hpp>
///#include <eve/function/swapbytes.hpp>
#include <eve/function/tofloat.hpp>
#include <eve/function/toint.hpp>
#include <eve/function/touint.hpp>
#include <eve/function/trunc.hpp>
#include <eve/function/two_add.hpp>
#include <eve/function/two_prod.hpp>
#include <eve/function/two_split.hpp>
#include <eve/function/ulpdist.hpp>
