####################################################################################################
##  EVE - Expressive Vector Engine
##  Copyright : EVE Project Contributors
##  SPDX-License-Identifier: BSL-1.0
####################################################################################################
name: EVE - Code coverage
on:
  pull_request:
    branches:
      - main

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: [self-hosted, avx512]
    container:
      image: ghcr.io/jfalcou/compilers:v7
      options: -u root
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: gcc , arch: x86, opts: -msse4.2  }
        - { comp: gcc , arch: x86, opts: -mavx2    }
        - { comp: gcc , arch: x86, opts: -march=skylake-avx512  }

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1
      - name: Running CMake for ${{ matrix.cfg.comp }} on ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DEVE_ENABLE_COVERAGE=ON -DEVE_OPTIONS="${{ matrix.cfg.opts }}" -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake
      - name: Compiling Unit Tests
        run:  cd build && ninja unit.exe -j 10
      - name: Running Unit Tests
        run: cd build && ctest --output-on-failure -j 10  -E ^doc.*.exe
      - name: Compile code coverage report
        run: lcov --directory . --capture --output-file coverage.info
      - name: Filter out system dependencies
        run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - name: Filter out tests files
        run: lcov --remove coverage.info '*.cpp' --output-file coverage.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
