####################################################################################################
##  EVE - Expressive Vector Engine
##  Copyright : EVE Project Contributors
##  SPDX-License-Identifier: BSL-1.0
####################################################################################################
name: EVE - Install Process
on:
  pull_request:
    branches:
      - main

concurrency:
  group: install-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##################################################################################################
  ## Check install process of EVE
  ##################################################################################################
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - {test: Installation       , mode: 0 }
        - {test: FetchContents      , mode: 1 }
        - {test: CPM                , mode: 2 }
        - {test: Multi-architecture , mode: 3 }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Check EVE Installation Procedure
        uses: ./.github/actions/integration
        with:
          branch: '${{ github.head_ref }}'
          mode: '${{ matrix.cfg.mode }}'
